version: '3.7'
services:
  redis:
    container_name: redis-compose
    image: redis:latest
    ports:
      - 6377:6379
    networks:
      - mynetwork
  app-golang:
    container_name: golang-compose
    image: app-golang:0.4
    ports:
      - 8007:8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      #- REDIS_PORT=6377
    networks:
      - mynetwork
networks: 
  mynetwork:
    name: mynetwork